import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowLeft, ArrowRight, Award, BookOpen, Check, CheckCircle2, ChevronRight, Clock3, Download, Flame, Flower2, Heart, HelpCircle, Leaf, Map, Pause, Play, RotateCcw, Search, Shuffle, Sparkles, Sprout, Star, Target, Trophy, Volume2, X } from 'lucide-react'
import KingdomArt from './components/KingdomArt'
import LearningBuddy, { AnimalPortrait, animalForGroup, Celebration } from './components/LearningBuddy'
import { allWords, charts, emptyProgress, lessons, lessonsForSymbol, localDate, makeQuestions, masteredLessons, parseProgress, shuffle, STORAGE_KEY, streak } from './learning'
import type { Lesson, Practice, Progress, Question, Word } from './learning'

const navItems = [
  { id:'learn', label:'学习乐园', icon:BookOpen }, { id:'chart', label:'拼音图谱', icon:Map },
  { id:'challenge', label:'趣味闯关', icon:Target }, { id:'favorites', label:'我的收藏', icon:Heart },
  { id:'progress', label:'成长足迹', icon:Sprout },
]
const groupColors: Record<string,string> = {'单韵母':'peach','声母':'sage','复韵母':'lavender','鼻韵母':'blue'}
const groups = ['全部课程','单韵母','声母','复韵母','鼻韵母']
const levelNames = { again:'再练一练',good:'基本会读',great:'熟练会读' }
const bookUrl = '/materials/pinyin-reader-2026.pdf'
function routeFromHash() { return window.location.hash.slice(1) || 'learn' }
function RubyText({word}:{word:Word}) {
  let i=0; const syllables=word.pinyin.split(' ')
  return <span className="ruby-line">{Array.from(word.hanzi).map((c,index)=> /[\u3400-\u9fff]/.test(c) ? <ruby key={index}>{c}<rt>{syllables[i++] || ''}</rt></ruby> : <span key={index}>{c}</span>)}</span>
}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {
  const ref=useRef<HTMLDialogElement>(null)
  useEffect(()=>{ const el=ref.current; el?.showModal(); return ()=>el?.close() },[])
  return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal-content"><div className="section-heading"><h2>{title}</h2><button className="icon-button" aria-label="关闭窗口" onClick={onClose}><X size={22}/></button></div>{children}</div></dialog>
}
export default function App() {
  const [route,setRoute]=useState(routeFromHash)
  const [progress,setProgress]=useState<Progress>(()=>{try{return parseProgress(localStorage.getItem(STORAGE_KEY))}catch{return emptyProgress()}})
  const [storageError,setStorageError]=useState(false)
  const [notice,setNotice]=useState('')
  const [guide,setGuide]=useState(false)
  const [confirmReset,setConfirmReset]=useState(false)
  const [filter,setFilter]=useState('全部课程')
  const [search,setSearch]=useState('')
  const [speaking,setSpeaking]=useState('')
  const [rate,setRate]=useState(0.75)
  const [chartType,setChartType]=useState<keyof typeof charts>('声母')
  const [symbol,setSymbol]=useState('')
  const speechTimer=useRef<ReturnType<typeof setTimeout> | undefined>(undefined)
  const pageTitle=useRef<HTMLHeadingElement>(null)
  const lessonId=Number(route.split('/')[1])
  const lesson=route.startsWith('lesson/') ? lessons.find(l=>l.id===lessonId) : undefined
  const activeNav=lesson ? 'learn' : route
  const mastered=masteredLessons(progress)
  const learnedCount=new Set(progress.practices.map(p=>p.lessonId)).size
  const stars=mastered.size*3+progress.quizStars
  const nextLesson=lessons.find(l=>!mastered.has(l.id)) || lessons[13]
  const suggested=progress.practices.length ? lessons[progress.lastLesson-1] : lessons[0]
  useEffect(()=>{const fn=()=>{setRoute(routeFromHash());setSearch('');setSymbol('');window.scrollTo(0,0);window.speechSynthesis?.cancel();setSpeaking('')};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[])
  useEffect(()=>{document.title=`${lesson ? lesson.title+' '+lesson.letters : navItems.find(n=>n.id===route)?.label || '学习乐园'} · 拼音王国`;pageTitle.current?.focus()},[route,lesson])
  useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));setStorageError(false)}catch{setStorageError(true)}},[progress])
  useEffect(()=>{if(notice){const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)}},[notice])
  useEffect(()=>()=>{window.speechSynthesis?.cancel();clearTimeout(speechTimer.current)},[])
  function go(id:string){if(route===id)window.scrollTo({top:0,behavior:'smooth'});else window.location.hash=id}
  function openLesson(id:number){setProgress(p=>({...p,lastLesson:id}));go(`lesson/${id}`)}
  function favorite(word:Word){setProgress(p=>({...p,favorites:p.favorites.includes(word.hanzi)?p.favorites.filter(f=>f!==word.hanzi):[...p.favorites,word.hanzi]}))}
  function speak(text:string) {
    if(!('speechSynthesis' in window)){setNotice('这个浏览器暂不支持朗读，请换用 Safari、Chrome 或 Edge。');return}
    window.speechSynthesis.cancel();clearTimeout(speechTimer.current)
    if(speaking===text){setSpeaking('');return}
    const voices=window.speechSynthesis.getVoices(); const voice=voices.find(v=>/zh[-_]CN/i.test(v.lang)) || voices.find(v=>/^zh/i.test(v.lang))
    if(voices.length&&!voice){setNotice('设备还没有中文语音，请在系统设置中添加普通话语音后重试。');setSpeaking('');return}
    const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';utterance.rate=rate;if(voice)utterance.voice=voice
    utterance.onend=()=>{setSpeaking('');clearTimeout(speechTimer.current)}
    utterance.onerror=(e)=>{setSpeaking('');clearTimeout(speechTimer.current);if(e.error!=='interrupted'&&e.error!=='canceled')setNotice('朗读暂时不可用，请检查设备的中文语音设置。')}
    // Some platforms load voices lazily; lang is kept as a fallback.
    utterance.onstart=()=>clearTimeout(speechTimer.current)
    setSpeaking(text);window.speechSynthesis.speak(utterance)
    speechTimer.current=setTimeout(()=>{window.speechSynthesis.cancel();setSpeaking('');setNotice('朗读未能启动，请检查设备的中文语音设置。')},10000)
  }
  function record(id:number,level:Practice['level']){setProgress(p=>({...p,lastLesson:id,practices:[...p.practices,{lessonId:id,date:localDate(),level}]}));setNotice('今天的努力已记下，给认真学习的你一朵小红花！')}
  const wordCard=(word:Word)=><div className="word-card" key={word.hanzi}><button className="word-read" onClick={()=>speak(word.hanzi)} aria-label={`朗读${word.hanzi}`}><RubyText word={word}/><Volume2 size={17} className={speaking===word.hanzi?'is-speaking':''}/></button><button className={`favorite-button ${progress.favorites.includes(word.hanzi)?'saved':''}`} aria-label={`${progress.favorites.includes(word.hanzi)?'取消收藏':'收藏'}${word.hanzi}`} aria-pressed={progress.favorites.includes(word.hanzi)} onClick={()=>favorite(word)}><Heart size={18}/></button></div>
  return <>
    <a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus()}}>跳到主要内容</a>
    <aside className="sidebar">
      <a className="brand" href="#learn" aria-label="拼音王国首页"><span className="brand-mark"><AnimalPortrait animal="fox"/></span><span>拼音王国<small>快乐拼读 · 自在成长</small></span></a>
      <div className="semester-label"><span/>一年级 · 上学期</div>
      <nav aria-label="主导航">{navItems.map(({id,label,icon:Icon})=><button key={id} className={`nav-item ${activeNav===id?'active':''}`} aria-current={activeNav===id?'page':undefined} onClick={()=>go(id)}><Icon size={21}/><span>{label}</span>{id==='learn'&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="little-note"><span className="note-sprout"><AnimalPortrait animal="frog"/></span><strong>每一天，都在长大</strong><p>不用着急，慢慢来。<br/>你的小进步，都很了不起。</p><span className="note-doodle">✧</span></div><button className="guide-link" onClick={()=>setGuide(true)}><HelpCircle size={18}/>家长陪学指南<ChevronRight size={16}/></button><div className="sidebar-foot">和小狐狸一起，爱上拼音</div></div>
    </aside>
    <div className="workspace">
      <header className="topbar"><div className="breadcrumb">拼音王国 <ChevronRight size={14}/><span>{lesson?'同步课堂':navItems.find(n=>n.id===route)?.label || '学习乐园'}</span></div><div className="topbar-right"><span className="header-streak"><Flame size={17}/>坚持 {streak(progress)} 天</span><span className="top-divider"/><span className="learner-avatar">☀</span><span className="learner-name">小小探索家</span></div></header>
      <main id="main-content" tabIndex={-1}>
        {storageError&&<div role="alert" className="storage-alert">浏览器无法保存学习记录。当前仍可学习，关闭页面后本次记录可能丢失。</div>}
        {activeNav==='learn'&&!lesson&&<>
          <div className="page-intro"><div><div className="eyebrow">欢迎来到拼音王国</div><h1 ref={pageTitle} tabIndex={-1}>你好呀，小小探索家 <span className="wave">✺</span></h1><p>今天也一起，发现拼音里的小小世界。</p></div><div className="date-chip"><Leaf size={16}/>每天一点点，进步看得见</div></div>
          <section className="hero"><div className="hero-copy"><span className="hero-tag"><Sparkles size={14}/>我的拼音奇妙之旅</span><h2>和拼音交朋友，<br/>一起<span>快乐大冒险！</span></h2><p>小狐狸和它的朋友们，正在等你！<br/>读一读、闯闯关，每天收获小进步。</p><button className="primary-button" onClick={()=>openLesson(suggested.id)}><Play size={16} fill="currentColor"/>{progress.practices.length?'继续学习':'开启学习之旅'}<ArrowRight size={17}/></button><span className="hero-caption">{progress.practices.length?'上次学到':'从这里出发'}：第 {suggested.id} 课 · {suggested.letters}</span></div><KingdomArt/><span className="hero-speech">一起出发吧！<span aria-hidden="true">✦</span></span></section>
          <div className="overview-stats"><Stat icon={<BookOpen/>} color="green" value={`${learnedCount}`} suffix="/ 14 课" title="已经探索"/><Stat icon={<Star/>} color="yellow" value={`${stars}`} suffix="颗" title="收集星星"/><Stat icon={<Flame/>} color="orange" value={`${streak(progress)}`} suffix="天" title="连续练习"/></div>
          <div className="learning-layout"><section className="courses-section"><div className="section-heading"><h2><BookOpen size={22}/>我的拼音课堂</h2><span className="muted small">和读本一起，一课一成长</span></div><div className="filter-tabs" aria-label="课程分类">{groups.map(g=><button key={g} className={filter===g?'selected':''} aria-pressed={filter===g} onClick={()=>setFilter(g)}>{g}</button>)}</div><div className="course-grid">{lessons.filter(l=>filter==='全部课程'||l.group===filter).map(l=><button className={`course-card ${groupColors[l.group]}`} key={l.id} onClick={()=>openLesson(l.id)}><div className="course-meta"><span className="course-number">第 {String(l.id).padStart(2,'0')} 课</span><span className="course-tag">{l.title}</span></div><div className="course-letter-row"><div className="course-letters">{l.letters}</div><AnimalPortrait animal={animalForGroup[l.group]} className="course-buddy"/></div><div className="course-description">{l.id<=2?'认识声调，读准每一个音':l.id<10?'认一认，拼一拼，读读词语':l.id<13?'小韵母手拉手，一起读一读':'听清鼻音，拼读更准确'}</div><div className="course-card-bottom"><span>{mastered.has(l.id)?<><CheckCircle2 size={14}/>熟练会读</>:progress.practices.some(p=>p.lessonId===l.id)?<><Sprout size={14}/>正在成长</>:<><Clock3 size={14}/>约 10 分钟</>}</span><span className="course-arrow"><ArrowRight size={17}/></span></div></button>)}</div><div className="source-note"><BookOpen size={15}/><span>课程依据《2026一上拼音读本（修改）》整理</span><a href={bookUrl} target="_blank" rel="noreferrer">查看原读本 ↗</a></div></section>
          <aside className="learning-side"><WeeklyCard progress={progress}/><div className="challenge-promo"><div className="promo-art"><AnimalPortrait animal="bear"/><span>✦</span><span>✧</span></div><span className="tiny-label">来点小挑战</span><h3>拼音小勇士，集合！</h3><p>5 道趣味小题，<br/>把学过的拼音再认识一遍。</p><button onClick={()=>go('challenge')}>去闯关<ArrowRight size={16}/></button></div><div className="tip-card"><span className="tip-label"><Flower2 size={18}/>陪学小贴士</span><h3>读一读，也动一动</h3><p>读声调时，用小手画一画：<br/>一声平，二声扬，<br/>三声拐弯，四声降。</p><button onClick={()=>setGuide(true)}>更多陪学建议 <ArrowRight size={15}/></button></div></aside></div>
        </>}
        {lesson&&<LessonView key={lesson.id} lesson={lesson} onBack={()=>go('learn')} onNext={()=>openLesson(Math.min(14,lesson.id+1))} onSpeak={speak} wordCard={wordCard} onRecord={level=>record(lesson.id,level)} practices={progress.practices.filter(p=>p.lessonId===lesson.id)} onQuizComplete={score=>setProgress(p=>({...p,quizStars:p.quizStars+score}))}/>}
        {route==='chart'&&<><PageIntro eyebrow="和拼音朋友见个面" title="拼音图谱" subtitle="认识每一位拼音朋友，点一点，找到它的课堂。"/><LearningBuddy message="我是小狐狸！挑一张字母卡，和我一起读读看。"/><section className="content-panel alphabet-panel"><div className="filter-tabs chart-tabs">{(Object.keys(charts) as (keyof typeof charts)[]).map(type=><button key={type} className={chartType===type?'selected':''} aria-pressed={chartType===type} onClick={()=>{setChartType(type);setSymbol('')}}>{type}<span>{charts[type].length}</span></button>)}</div><div className="alphabet-grid">{charts[chartType].map(s=><button key={s} className={s===symbol?'chosen':''} onClick={()=>setSymbol(s)} aria-pressed={s===symbol}><span className="alphabet-letter">{s}</span><span className="letter-face" aria-hidden="true"><i/><i/><b/></span></button>)}</div>{symbol?<div className="symbol-detail"><span className="big-symbol">{symbol}</span><div><h3>你好，{symbol}！</h3><p>{chartType==='整体认读音节'?'整体认读音节直接读，不要拆开拼读。':lessons[lessonsForSymbol(symbol)-1].tip}</p></div><button className="primary-button" onClick={()=>openLesson(lessonsForSymbol(symbol))}>去课堂练习<ArrowRight size={17}/></button></div>:<div className="gentle-hint"><Sparkles size={18}/>点一个拼音，开始认识它吧。</div>}</section><section className="tone-guide"><h2>声调的小秘密</h2><div className="tone-cards">{['ā','á','ǎ','à'].map((s,i)=><div key={s}><span className="tone-symbol">{s}</span><svg className="tone-trail" viewBox="0 0 100 40" fill="none" aria-hidden="true"><path d={["M10 20H88", "M10 32L87 8", "M10 10L48 32L87 8", "M10 8L88 32"][i]}/><circle cx="10" cy={[20,32,10,8][i]} r="4"/></svg><h3>第{['一','二','三','四'][i]}声</h3><p>{['高高平又平','爬坡向上扬','拐弯下又上','下坡快又响'][i]}</p></div>)}</div></section></>}
        {route==='challenge'&&<><PageIntro eyebrow="小勇士，准备出发" title="拼音小勇士" subtitle="不怕答错，每一次尝试都能让你更进步。"/><LearningBuddy animal="bear" message="我来当你的加油队！看清拼音，再选一选。"/><Quiz onComplete={score=>setProgress(p=>({...p,quizStars:p.quizStars+score}))} onSpeak={speak}/><div className="gentle-hint"><Heart size={18}/>没有倒计时，慢慢想。答错后会看到正确答案。</div></>}
        {route==='favorites'&&<><PageIntro eyebrow="装满喜欢的小宝箱" title="我的词语收藏夹" subtitle="把想多读几遍的词语放在这里，随时回来复习。"/><div className="section-heading"><span className="muted">收藏了 {progress.favorites.length} 个词语</span><label className="search-field"><Search size={18}/><input aria-label="搜索收藏词语" placeholder="找一找词语或拼音" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{progress.favorites.length?<><div className="word-grid favorite-grid">{allWords.filter(w=>progress.favorites.includes(w.hanzi)&&(w.hanzi.includes(search)||w.pinyin.toLowerCase().includes(search.toLowerCase()))).map(wordCard)}</div>{!allWords.some(w=>progress.favorites.includes(w.hanzi)&&(w.hanzi.includes(search)||w.pinyin.toLowerCase().includes(search.toLowerCase())))&&<div className="empty-state"><Search size={36}/><h2>还没找到这个词语</h2><p>试试别的字，或者清空搜索。</p><button className="secondary-button" onClick={()=>setSearch('')}>清空搜索</button></div>}</>:<div className="empty-state"><Heart size={48}/><AnimalPortrait animal="bunny" className="empty-buddy"/><h2>给喜欢的词语，一颗小爱心</h2><p>进入课堂，在“词句阅读”里点击爱心，就能在这里找到它。</p><button className="primary-button" onClick={()=>openLesson(3)}>去读读词语<ArrowRight size={17}/></button></div>}</>}
        {route==='progress'&&<><PageIntro eyebrow="我的进步，会发光" title="我的成长足迹" subtitle="每一次认真开口，都是值得记住的小进步。"/><div className="overview-stats"><Stat icon={<BookOpen/>} color="green" value={`${mastered.size}`} suffix="/ 14 课" title="熟练会读"/><Stat icon={<Star/>} color="yellow" value={`${stars}`} suffix="颗" title="收集星星"/><Stat icon={<Flower2/>} color="orange" value={`${progress.practices.length}`} suffix="遍" title="累计练习"/></div><div className="progress-columns"><section className="content-panel"><div className="section-heading"><h2>我的学习路线</h2><span>{Math.round(mastered.size/14*100)}%</span></div><div className="progress-track"><div style={{width:`${mastered.size/14*100}%`}}/></div><div className="lesson-checklist">{lessons.map(l=><button key={l.id} onClick={()=>openLesson(l.id)}><span className={`checklist-icon ${mastered.has(l.id)?'done':''}`}>{mastered.has(l.id)?<Check size={17}/>:l.id}</span><span>{l.title}<strong>{l.letters}</strong></span><span className="checklist-state">{levelNames[progress.practices.findLast(p=>p.lessonId===l.id)?.level as Practice['level']] || '等你探索'}</span><ChevronRight size={16}/></button>)}</div></section><div><WeeklyCard progress={progress}/><section className="content-panel badge-panel"><h2>成长徽章</h2><div className="badge-row">{[{icon:Sprout,name:'初次出发',earned:progress.practices.length>0,tip:'完成一次朗读记录'},{icon:Flame,name:'三日小能手',earned:streak(progress)>=3,tip:'连续练习 3 天'},{icon:Award,name:'拼音小达人',earned:mastered.size===14,tip:'14 课都熟练会读'}].map(({icon:Icon,name,earned,tip})=><div key={name} className={`badge ${earned?'earned':''}`}><Icon size={34}/><strong>{name}</strong><small>{earned?'已点亮':tip}</small></div>)}</div></section><section className="content-panel recent-panel"><h2>最近的努力</h2>{progress.practices.length?<ul>{progress.practices.slice(-5).reverse().map((p,i)=><li key={i}><Flower2 size={17}/><span>第 {p.lessonId} 课 · {levelNames[p.level]}<small>{p.date}</small></span></li>)}</ul>:<p className="muted">第一次练习，正在等你出发。</p>}<button className="primary-button" onClick={()=>openLesson(nextLesson.id)}>继续探索<ArrowRight size={17}/></button></section></div></div><div className="data-note"><p>学习记录仅保存在当前浏览器，不收集孩子的姓名、声音或照片。</p><button className="text-button" onClick={()=>setConfirmReset(true)}>清空本机学习记录</button></div></>}
        {!lesson&&!navItems.some(n=>n.id===route)&&<div className="empty-state"><Map size={48}/><h1>这条小路还没有开通</h1><button className="primary-button" onClick={()=>go('learn')}>回到学习乐园</button></div>}
        <footer className="page-footer"><span><Sprout size={15}/>每一颗小种子，都有自己的花期。</span><button onClick={()=>setGuide(true)}>家长陪学指南</button></footer>
      </main>
    </div>
    {notice&&<div className="toast" role="status"><Flower2 size={21}/>{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    {speaking&&<div className="audio-status" role="status"><Volume2 size={17}/>正在朗读：{speaking}<button aria-label="停止朗读" onClick={()=>{window.speechSynthesis.cancel();setSpeaking('')}}><Pause size={17}/></button></div>}
    {guide&&<Modal title="一起陪伴，一起成长" onClose={()=>setGuide(false)}><p className="guide-intro">把学习变成每天 10 分钟的亲子时光。</p><ol className="guide-steps"><li><strong>先认一认，再读一读</strong><p>按照原读本的顺序学习。拼音练习支持顺着读、倒着读和打乱读；单个拼音请由家长或老师带读。</p></li><li><strong>听词语，再自己开口</strong><p>点击词语和句子的喇叭可听设备提供的中文合成语音。多音字、轻声和变调可能因设备而异，请以老师示范和教材标注为准；本站不做语音评分。</p><label className="rate-control">朗读速度<select aria-label="朗读速度" value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="0.6">慢一点</option><option value="0.75">适合跟读</option><option value="1">正常速度</option></select></label></li><li><strong>让每一点努力被看见</strong><p>每读完一遍，在课堂底部选择掌握程度并记录。熟练会读的课程可点亮 3 颗星，闯关每答对一题可获得 1 颗星。</p></li><li><strong>保护小眼睛</strong><p>每次学习 10–15 分钟后，看看远处、动动身体。所有学习记录仅保存在当前浏览器；换设备不会自动同步。</p></li></ol><a className="secondary-button download-link" href={bookUrl} target="_blank" rel="noreferrer"><Download size={18}/>打开原版拼音读本</a></Modal>}
    {confirmReset&&<Modal title="清空这台设备的学习记录？" onClose={()=>setConfirmReset(false)}><p>将清空练习记录、收藏、星星和徽章。这个操作无法撤销。</p><div className="modal-actions"><button className="secondary-button" onClick={()=>setConfirmReset(false)}>保留记录</button><button className="danger-button" onClick={()=>{setProgress(emptyProgress());setConfirmReset(false);setNotice('本机学习记录已清空，可以重新出发啦。')}}>确认清空</button></div></Modal>}
  </>
}
function PageIntro({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div className="page-intro secondary-intro"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div></div>}
function Stat({icon,color,value,suffix,title}:{icon:ReactNode;color:string;value:string;suffix:string;title:string}){return <div className="stat-card"><span className={`stat-icon ${color}`}>{icon}</span><div><span className="stat-title">{title}</span><div className="stat-value">{value}<span>{suffix}</span></div></div><span className="stat-decoration">✧</span></div>}
function WeeklyCard({progress}:{progress:Progress}) {
  const today=new Date(); const monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7)); const days=new Set(progress.practices.map(p=>p.date)); const week=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return {date:localDate(d),label:['一','二','三','四','五','六','日'][i]}})
  return <section className="weekly-card"><div className="section-heading"><h3><span className="small-sun">☀</span>这周也很棒</h3><span className="tiny-label">学习打卡</span></div><div className="week-days">{week.map(d=><div key={d.date}><span>{d.label}</span><div aria-label={`${d.date}${days.has(d.date)?'已练习':'未练习'}`} className={`day-circle ${days.has(d.date)?'checked':''} ${d.date===localDate()?'today':''}`}>{days.has(d.date)?<Check size={15}/>:d.date===localDate()?<span/>:'·'}</div></div>)}</div><p>本周已练习 <strong>{week.filter(d=>days.has(d.date)).length}</strong> 天，<br/>每次开口，都值得一朵小红花。</p><div className="week-bottom"><Flower2 size={18}/>今天也给自己一个鼓励</div></section>
}
function LessonView({lesson,onBack,onNext,onSpeak,wordCard,onRecord,practices,onQuizComplete}:{lesson:Lesson;onBack:()=>void;onNext:()=>void;onSpeak:(t:string)=>void;wordCard:(w:Word)=>ReactNode;onRecord:(l:Practice['level'])=>void;practices:Practice[];onQuizComplete:(s:number)=>void}) {
  const [tab,setTab]=useState('read'); const [order,setOrder]=useState(lesson.syllables); const [selected,setSelected]=useState('');const [level,setLevel]=useState<Practice['level']>('good');const [saved,setSaved]=useState(false)
  return <>
    <button className="back-button" onClick={onBack}><ArrowLeft size={17}/>回到拼音课堂</button>
    <div className={`lesson-header ${groupColors[lesson.group]}`}><div><span className="eyebrow">第 {String(lesson.id).padStart(2,'0')} 课 · 原读本第 {lesson.page} 页</span><h1>{lesson.title}<span>{lesson.letters}</span></h1><p>{lesson.tip}</p></div><a href={`${bookUrl}#page=${lesson.page}`} target="_blank" rel="noreferrer" className="source-button"><BookOpen size={17}/>对照原读本</a></div>
    <div className="lesson-tabs" role="tablist" aria-label="学习步骤">{[{id:'read',label:'认读与拼读',icon:BookOpen},{id:'words',label:'词句阅读',icon:Volume2},{id:'quiz',label:'小小挑战',icon:Target}].map(({id,label,icon:Icon})=><button key={id} id={`tab-${id}`} role="tab" aria-selected={tab===id} aria-controls={`panel-${id}`} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon size={18}/>{label}</button>)}</div>
    <div role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>
    {tab==='read'&&<><section className="content-panel recognition-panel"><div className="section-heading"><h2>01 <span>{lesson.id<=2?'认识四个声调':'准确认读'}</span></h2><span className="muted small">请家长或老师带读</span></div><div className="recognition-text">{lesson.recognition}</div></section><section className="content-panel"><div className="section-heading reading-heading"><h2>02 <span>我会读一读</span></h2><div className="reading-controls"><button onClick={()=>{setOrder(lesson.syllables);setSelected('')}}><RotateCcw size={15}/>顺着读</button><button onClick={()=>{setOrder([...order].reverse());setSelected('')}}><ArrowLeft size={15}/>倒着读</button><button onClick={()=>{setOrder(shuffle(order));setSelected('')}}><Shuffle size={15}/>打乱读</button></div></div><p className="muted small">点一点，选中一个拼音。看清声调，大声读出来。</p><div className="syllable-grid">{order.map((s,i)=><button key={`${s}-${i}`} className={selected===`${i}`?'selected':''} aria-pressed={selected===`${i}`} onClick={()=>setSelected(`${i}`)}>{s}</button>)}</div>{selected&&<div className="reading-hint" role="status"><Sparkles size={17}/>现在轮到 <strong>{order[Number(selected)]}</strong> 啦，试着自己读一读。</div>}</section>{lesson.comparisons.length>0&&<section className="content-panel"><h2>03 <span>比一比，读一读</span></h2><div className="comparison-grid">{lesson.comparisons.map((p,i)=><div key={i}>{p}</div>)}</div></section>}</>}
    {tab==='words'&&<>{lesson.words.length?<><section className="content-panel"><div className="section-heading"><h2>读读词语</h2><span className="muted small">点词语听朗读 · 点爱心加入收藏</span></div><div className="word-grid">{lesson.words.map(wordCard)}</div><p className="audio-note">词语朗读使用设备的中文合成语音，轻声和多音字请结合拼音标注与老师示范。</p></section>{lesson.sentences.length>0&&<section className="content-panel"><h2>把词语连成一句话</h2><div className="sentence-list">{lesson.sentences.map(s=><button key={s.hanzi} onClick={()=>onSpeak(s.hanzi)} aria-label={`朗读${s.hanzi}`}><RubyText word={s}/><Volume2 size={20}/></button>)}</div></section>}<section className="content-panel"><h2>认读生字，再组个词</h2><div className="character-grid">{Array.from(lesson.characters).map(c=><span key={c}>{c}</span>)}</div><p className="muted">试着用上面的生字说一个词语，讲给身边的人听。</p></section></>:<section className="content-panel tone-empty"><Flower2 size={40}/><h2>先和单韵母做好朋友</h2><p>这节课没有词语练习。先读准四声，再去“小小挑战”找声调。</p><button className="primary-button" onClick={()=>setTab('quiz')}>去找一找声调<ArrowRight size={17}/></button></section>}</>}
    {tab==='quiz'&&<Quiz lesson={lesson} onComplete={onQuizComplete} onSpeak={onSpeak}/>}
    </div>
    <section className="practice-record"><div><span className="record-flower"><AnimalPortrait animal="frog"/></span><h2>读完一遍，记下小进步</h2><p>这一课已练习 {practices.length} 遍。请和家长一起选一选。</p></div><div className="record-options"><div className="rating-buttons">{(['again','good','great'] as const).map(l=><button key={l} className={level===l?'active':''} aria-pressed={level===l} onClick={()=>{setLevel(l);setSaved(false)}}>{levelNames[l]}</button>)}</div><button className={`primary-button ${saved?'record-saved':''}`} disabled={saved} onClick={()=>{onRecord(level);setSaved(true)}}><Check size={17}/>{saved?'这一遍已记录':'记录这次练习'}</button>{saved&&<button className="text-button" onClick={()=>setSaved(false)}>再读一遍，继续记录</button>}</div></section>
    <div className="lesson-next"><button className="text-button" onClick={onBack}><ArrowLeft size={16}/>返回课程</button>{lesson.id<14&&<button className="secondary-button" onClick={onNext}>下一课：{lessons[lesson.id].letters}<ArrowRight size={17}/></button>}</div>
  </>
}
function Quiz({lesson,onComplete,onSpeak}:{lesson?:Lesson;onComplete:(s:number)=>void;onSpeak:(t:string)=>void}) {
  const [questions,setQuestions]=useState<Question[]>(()=>makeQuestions(lesson));const [index,setIndex]=useState(0);const [choice,setChoice]=useState<string|null>(null);const [score,setScore]=useState(0);const [finished,setFinished]=useState(false);const answered=useRef(false);const reported=useRef(false);const q=questions[index]
  function choose(value:string){if(answered.current)return;answered.current=true;setChoice(value);if(value===q.answer)setScore(s=>s+1)}
  function next(){if(!answered.current)return;if(index===questions.length-1){setFinished(true);if(!reported.current){reported.current=true;onComplete(score)}}else{setIndex(i=>i+1);setChoice(null);answered.current=false}}
  function restart(){setQuestions(makeQuestions(lesson));setIndex(0);setChoice(null);setScore(0);setFinished(false);answered.current=false;reported.current=false}
  if(finished)return <section className="quiz-card quiz-result"><Celebration/><div className="result-trophy"><AnimalPortrait animal="bear"/><Trophy size={32}/></div><span className="eyebrow">每一次尝试，都值得鼓励</span><h2>{score===questions.length?'太棒啦，全部答对！':'完成啦，又进步了一点！'}</h2><div className="result-stars">{Array.from({length:questions.length},(_,i)=><Star key={i} size={35} fill={i<score?'currentColor':'none'} className={i<score?'earned':''}/>)}</div><p>答对 {score} / {questions.length} 题，收集了 {score} 颗星星。</p><p className="muted">{score===questions.length?'把这份小小成就，分享给家人吧。':'没记住的拼音，回到课堂再读一遍就好。'}</p><button className="primary-button" onClick={restart}><RotateCcw size={17}/>再挑战一次</button></section>
  return <section className="quiz-card"><div className="quiz-top"><span><Target size={19}/>{lesson?`第 ${lesson.id} 课的小挑战`:'词语拼音大挑战'}</span><span>第 {index+1} / {questions.length} 题</span></div><div className="quiz-progress">{questions.map((_,i)=><span key={i} className={i<=index?'filled':''}/>)}</div><div className="quiz-question"><span className="question-badge">{q.word?'选一选':'认一认'}</span><h2>{q.prompt}</h2>{q.word&&<button className="listen-button" onClick={()=>onSpeak(q.word!)}><Volume2 size={18}/>听听这个词</button>}</div><div className="answer-grid">{q.choices.map((c,i)=><button key={c} disabled={choice!==null} onClick={()=>choose(c)} className={`${choice!==null&&c===q.answer?'correct':''} ${choice===c&&c!==q.answer?'incorrect':''}`}><span className="answer-letter">{String.fromCharCode(65+i)}</span><span>{c}</span>{choice!==null&&c===q.answer&&<CheckCircle2 size={20}/>}</button>)}</div>{choice!==null?<div className={`answer-feedback ${choice===q.answer?'success':''}`} role="status"><div><strong>{choice===q.answer?'答对啦，真棒！':'没关系，一起来记住它。'}</strong><p>{q.explanation}</p></div><button className="primary-button" onClick={next}>{index===questions.length-1?'看看我的收获':'下一题'}<ArrowRight size={17}/></button></div>:<div className="quiz-bottom"><Leaf size={16}/>仔细看一看，再选出你的答案。</div>}</section>
}
